name: zimbobwade
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7069745762273669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#46618c'
    - '#5487cc'
    - '#0d0d0f'
    - '#a7bde6'
    - '#e8dfc0'
  brandStrength: 0.5
  lightness: 0.43540775985457003
  saturation: 0.4156837956979871
  rhythmicContrast: 0.8289541280828416
purpose: []
