name: zimbobwade
favicon: null
layout_spectrum: 0.945238662417978
typography_spectrum: 0.7069745762273669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9330269272904843
  lightness: 0.43540775985457003
  saturation: 0.4156837956979871
  rhythmicContrast: 0.8289541280828416
purpose: []
